# -*- coding: utf-8 -*-
"""Capstone Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWNfIWxZEPz6ai3GhNxmXeh87E8s2D2w
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/penguins_size.csv")

sns.get_dataset_names()

df = sns.load_dataset('penguins')
df.head(10)

df.shape

df.tail()

df.isnull().sum()

df.describe().T

df.describe()

df.dtypes

df.info()

df.isnull().sum()

df.describe(include='all')

sns.heatmap(df.corr(), cmap= 'Wistia', annot=True);

df.corr()

df.hist(figsize=(12,8));

df.plot(kind= 'box', subplots=True, layout=(3, 2), sharex=False, sharey= False, figsize=(8,12))

df.sex.value_counts()

df.island.value_counts()

df.species.value_counts()

sns.countplot(data=df, x='sex', palette='summer');

sns.countplot(data=df, x='island', palette='RdPu');

sns.countplot(data=df, x='species', palette='YlOrRd');

sns.countplot(data=df, x='sex', palette='rocket', hue='species');

sns.countplot(data=df, x='island', palette='husl', hue='species');

sns.countplot(data=df, x='island', palette='spring', hue='sex');

sns.pairplot(data=df, palette='mako', hue='species');