# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-av_sj3fa0bBvKKIi5RIUtf2L4eqH2i1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/IMDB Dataset.csv")

df.head(3)
df.tail(3)
df.info()
df.isnull().sum()

subset_df = df.iloc[41:76]
subset_df

df[df["No_of_Votes"] == df["No_of_Votes"].max()]

sns.boxplot(x=df["IMDB_Rating"])
sns.boxplot(x=df["Runtime"])

plt.figure(figsize=(8, 6))
plt.scatter(df["Runtime"], df["IMDB_Rating"])
plt.xlabel("Runtime")
plt.ylabel("IMDB Rating")
plt.title("Runtime vs IMDB Rating")

sns.histplot(df["IMDB_Rating"], kde=True)
sns.histplot(df["Runtime"], kde=True)

sns.countplot(x=df["Certificate"])